name: build-matrix

on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

jobs:
  build:
    env:
      BUILD: "build"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo test
        run: |
          echo BUILD=${{ env.BUILD }}
          echo VARIABLE=${{ env.VARIABLE }}
        env:
          BUILD1: "VARIABLE"
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cargo
            ~/.rustup
            CARGO_TARGET_DIR
          key: ${{ runner.os }}-deps

      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          set-safe-directory: 'true'

      - uses: actions-rs/toolchain@v1.0.6
        #if: ${{ !env.ACT }}
        with:
          toolchain: nightly
          default: true
          override: true

      - name: echo BUILD
        run: |
          echo $BUILD

      - name: echo VARIABLE
        run: |
          echo $VARIABLE

      - name: brew install docker
        run: |
          if [[   "$(uname -s)" == "Darwin" ]];then brew install docker; fi

      - name: which docker
        run: |
          if [[ ! "$(uname -s)" == "Darwin" ]];then echo $(which docker); fi

      - name: command -v docker
        run: |
          if [[ ! "$(uname -s)" == "Darwin" ]];then echo $(command -v docker); fi

      - name: apt-get update || brew install virtualenv
        run: |
          sudo apt-get update || brew install virtualenv
          python3 -m pip install virtualenv
          printenv
          V=1 make
          V=1 make help
          V=1 make report
          if [[ ! "$(uname -s)" == "Darwin" ]];then V=1 make; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then V=1 make all; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then V=1 make mint-000; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then V=1 make mint-001; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then V=1 make mint-002; fi
          ./miniscript-docker
          if [[ ! "$(uname -s)" == "Darwin" ]];then ./miniscript-docker; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then miniscript-docker; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then miniscript-docker help; fi
          if [[ ! "$(uname -s)" == "Darwin" ]];then miniscript-docker example; fi

      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cargo
            ~/.rustup
            CARGO_TARGET_DIR
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

